apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.3  # Correct image version
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: my-config
          mountPath: /etc/nginx/conf.d
        - name: html-volume
          mountPath: /usr/cko-share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: html-volume
        configMap:
          name: html-config
