version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - '8055:8080'
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  tflocal:
    container_name: tflocal
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - localstack
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566  # Use service name to refer to localstack
      # - AWS_ACCESS_KEY_ID=test
      # - AWS_SECRET_ACCESS_KEY=test
      # - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - .:/workspace  # Mount the current directory to /workspace
    working_dir: /workspace
    entrypoint: ["/bin/sh", "-c", "while true; do sleep 30; done"] # Keep the container running
